sudo: false
addons:
  sonarcloud:
    token: ${SONAR_TOKEN}
jdk:
  - openjdk11
language: java
script:
  - mvn test
  - sonar-scanner -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=anxoportela -Dsonar.projectKey=ejemploMaven